_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.11.11
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 41
                - 55
            "3":
                - 2
                - 17
                - 23
                - 55
            "4": 3.11.11
            "5": 0.19.8
            "8":
                - 3
                - 5
            "12": 0.19.8
            "13": windows-amd64
early_stop:
    value: 3
learning_rate:
    value: 0.009966
momentum:
    value: 0.746802
num_epochs:
    value: 10
